name: Compile

on:
  pull_request:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux-arm64, linux-x64, windows-x64, darwin-arm64, darwin-x64]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun build src/index.ts --compile --target=bun-${{ matrix.target }} --outfile out/gg-${{ matrix.target }}

