name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-releases:
    name: Publish binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [linux-arm64, linux-x64, windows-x64, darwin-arm64, gg-darwin-x64]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Build
        run: |
          bun build src/index.ts --compile --target=bun-${{ matrix.target }} --outfile out/${{ matrix.target }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/gg-${{ matrix.target }}
          asset_name: ${{ matrix.target }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Binary release for ${{ matrix.target }}"