name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint:check
      - run: bun run tsc
      - run: bun run build
      - run: bun run build:linux-arm64
      - run: |
          set -ex
          ls -l out/gg-linux-arm64
          ./out/gg-linux-arm64 --version
          echo $PATH
      - run: bun test

