name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint:check
      - run: bun run tsc
      - run: bun run build
      - run: bun run build:linux-x64
      - name: Compile and install
        run: |
          set -ex
          ls -l out/gg-linux-x64
          ./out/gg-linux-x64 --version
          pwd
          whoami
          echo $PATH
          mv out/gg-linux-x64 /home/runner/.local/bin/gg
          gg --version
      - run: bun test

